import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModel";
import CheckoutPage from "./components/checkout";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    
       <CartProvider>
       <Navbar />
       <CheckoutPage />
       
       <ShoppingCartModal/>
        {children}
       </CartProvider>
        </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import CartProvider from "./components/Providers";
// import ShoppingCartModal from "./components/ShoppingCartModel";
// import { useNavigation } from "next/navigation"; // Import useNavigation hook
// import CheckoutPage from "./components/checkout";
// import { useNavigation } from "next/navigation";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const navigation = useNavigation(); // Get navigation object

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CartProvider>
//           <Navbar />
//           <ShoppingCartModal />
//           {children}
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
