import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModel";
import { useRouter } from "next/router";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const isCheckoutPage = router.pathname === "/checkout"; 
  return (
    <html lang="en">
      <body className={inter.className}>
      {!isCheckoutPage && <Navbar />}    
       <CartProvider>
       <Navbar />         
       <ShoppingCartModal/>
        {children}
       </CartProvider>
        </body>
    </html>
  );
}

