// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import CartProvider from "./components/Providers";
// import ShoppingCartModal from "./components/ShoppingCartModel";
// import { useRouter } from "next/router";



// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const router = useRouter();
//   const isCheckoutPage = router.pathname === "/checkout"; 
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       {!isCheckoutPage && <Navbar />}    
//        <CartProvider>
//        <Navbar />         
//        <ShoppingCartModal/>
//         {children}
//        </CartProvider>
//         </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import NextScript from "next/script";
import { useNavigation } from "next/navigation"; // Import useNavigation hook
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = useNavigation(); // Initialize useNavigation hook
  const isCheckoutPage = navigation.pathname === "/checkout"; // Use navigation.pathname to get current path

  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <style>{inter.getStyleTag()}</style>
      </Head>
      <body>
        <CartProvider>
          {!isCheckoutPage && <Navbar />}         
          <ShoppingCartModal/>
          {children}
        </CartProvider>
        <NextScript />
      </body>
    </html>
  );
}
